config/routes.rb
Rails.application.routes.draw do
	get '/' => 'index#index'
	get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'

  resources :posts
  # get '/posts' => 'posts#index'
  # get '/posts/:id' => 'posts#show'
  # get '/posts/new' => 'posts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
  has_many :posts

	validates :username, :email, presence: true, uniqueness: true
	validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    require_user
  end

  def create
    require_user
    post = Post.new(post_params)
    if post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def edit
    require_user
    @post = Post.find(params[:id])
  end

  def update
    require_user
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    require_user
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

   def post_params
     params.require(:post).permit(:title, :body, :user_id)
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(username: params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id 
			redirect_to '/'
		else
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:logged_out] = "You have successfully logged out!"
		redirect_to '/'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to '/'
		else
			render 'new'
		end
	end

	private

		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/index/index.html.erb
This is an index page!<br>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
 <% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
        <ul>
          <li><%= link_to 'Home', '/' %></li>
          <li><%= link_to 'Posts', posts_path %>
          <% if current_user %>
            <li><%= link_to 'New Post', new_post_path %></li>
            <li><%= link_to 'Log Out', logout_path %></li>
          <% else %>
            <li><%= link_to "Create Account", users_new_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
          <% end %>

        </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post: <%=@post.title%></h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>All Posts:</h1>
<ul>
<% @posts.each do |post| %>
  <li><a href="/posts/<%=post.id%>"><%= post.title %></a></li>
<% end %>
</ul>

app/views/posts/new.html.erb
<h1>Create A New Post</h1>
<%= form_for :post, url: '/posts', :html => {:class => 'new-post-form'} do |f| %>
  Title: <%= f.text_field :title %><br>
  Body: <%= f.text_area :body %><br>
  <%= hidden_field(:user_id, current_user.id) %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p>
by: <%= @user.username %><br>
posted: <%= @post.created_at %>
</p>
<p><%= @post.body %></p>
<% if current_user && @post.user_id == current_user.id %>
<p>
  <%= link_to 'Edit', edit_post_path %><br>
  <%= link_to 'Delete Post', {:controller=>:posts,:action=>:destroy, :id=>@post}, :method=>:delete %>
</p>
<% end %>

app/views/users/new.html.erb
<h1>Create A New Account</h1>
<%= form_for :user, url: users_new_path, :html => {:class => 'new-user-form'} do |f| %>
	Username: <%= f.text_field :username %><br>
	Email: <%= f.text_field :email %><br>
	Password: <%= f.password_field :password %><br>
	<%= f.submit "Submit" %>
<% end %>